# Generated by Django 2.0.2 on 2018-04-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180409_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_type',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], default='alipay', max_length=10, verbose_name='支付类型'),
        ),
    ]
